---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos-7
    image: quay.io/paulfantom/molecule-systemd:centos-7
    pre_build_image: true
    tmpfs:
      - /run
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /sbin/init
  - name: centos-8
    image: quay.io/paulfantom/molecule-systemd:centos-8
    pre_build_image: true
    tmpfs:
      - /run
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /sbin/init
  - name: debian-10
    image: quay.io/paulfantom/molecule-systemd:debian-10
    pre_build_image: true
    tmpfs:
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /sbin/init
  - name: debian-9
    image: quay.io/paulfantom/molecule-systemd:debian-9
    pre_build_image: true
    tmpfs:
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /sbin/init
  - name: ubuntu-18-04
    image: quay.io/paulfantom/molecule-systemd:ubuntu-18.04
    pre_build_image: true
    tmpfs:
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /sbin/init
provisioner:
  name: ansible
verifier:
  name: ansible
  # enabled: False
lint: |
  yamllint .
